### ISSUE TITLE
[MSHADE-255] IllegalArgumentException on relocating class

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-shade-plugin#282]
**[eliuser2](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=eliuser2)** opened **[MSHADE-255](https://issues.apache.org/jira/browse/MSHADE-255?redirect=false)** and commented

```xml
<executions>
                    <execution>
                            <phase>package</phase>
                            <goals>
                                    <goal>shade</goal>
                            </goals>
                            <!---->
                            <configuration>
                                    <relocations>
                                            <relocation>
                                                    <pattern>org.jdom</pattern>
                                                    <shadedPattern>my.company.shaded.org.jdom</shadedPattern>
                                            </relocation>
                                    </relocations>
                            </configuration>
                            <!---->
                    </execution>
            </executions>
```

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade (default) on project spark-uberjar: Error creating shaded jar: null: IllegalArgumentException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade (default) on project spark-uberjar: Error creating shaded jar: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating shaded jar: null
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:546)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.apache.maven.plugins.shade.DefaultShader.addRemappedClass(DefaultShader.java:418)
	at org.apache.maven.plugins.shade.DefaultShader.shadeSingleJar(DefaultShader.java:220)
	at org.apache.maven.plugins.shade.DefaultShader.shadeJars(DefaultShader.java:181)
	at org.apache.maven.plugins.shade.DefaultShader.shade(DefaultShader.java:104)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:442)
	... 22 more
```

---

**Affects:** 3.0.0

**Issue Links:**
- [MSHADE-258](https://issues.apache.org/jira/browse/MSHADE-258) RemappingClassAdapter is deprecated and throws an exception with ASM 6.0 beta
 (_**"is superceded by"**_)

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Should be fixed with MSHADE-258
