### ISSUE TITLE
[MSHADE-9] failure to shade/relocate plexus-archiver (interfaces not properly relocated)

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-shade-plugin#362]
**[Daniel Fabulich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dfabulich)** opened **[MSHADE-9](https://issues.apache.org/jira/browse/MSHADE-9?redirect=false)** and commented

I tried using the shade plugin with surefire, to shade/relocate plexus-archiver.  I'm trying to relocate its package to be org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.  It took several tries due to MSHADE-5, but even when it finally "worked", it failed to modify plexus-archiver correctly.

org.codehaus.plexus.archiver.zip.AsiExtraField implements org.codehaus.plexus.archiver.zip.ZipExtraField.  But when I try to run p-archiver after shading it, I get this exception:

java.lang.ExceptionInInitializerError
at org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.zip.ZipEntry.getCentralDirectoryExtra(ZipEntry.java:386)
at org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.zip.ZipOutputStream.writeCentralFileHeader(ZipOutputStream.java:769)
at org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.zip.ZipOutputStream.finish(ZipOutputStream.java:320)
at org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.zip.ZipOutputStream.close(ZipOutputStream.java:542)
at org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchiveMain(AbstractZipArchiver.java:378)
at org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.zip.AbstractZipArchiver.createArchive(AbstractZipArchiver.java:250)
at org.apache.maven.surefire.booter.ForkConfiguration.createJar(ForkConfiguration.java:264)
[snip]
Caused by: java.lang.RuntimeException: class org.codehaus.plexus.archiver.zip.AsiExtraField doesn't implement ZipExtraField
at org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.zip.ExtraFieldUtils.register(ExtraFieldUtils.java:63)
at org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.zip.ExtraFieldUtils.\<clinit>(ExtraFieldUtils.java:43)
... 31 more

My decompiler (DJ) shows that the interfaces were partially but not entirely shaded correctly:

package org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.zip;

import java.util.zip.CRC32;
import java.util.zip.ZipException;
import org.codehaus.plexus.archiver.UnixStat;
import org.codehaus.plexus.archiver.zip.ZipExtraField;
import org.codehaus.plexus.archiver.zip.ZipLong;
import org.codehaus.plexus.archiver.zip.ZipShort;

// Referenced classes of package org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.zip:
//            ZipExtraField, ZipShort, ZipLong

public class AsiExtraField
implements org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.zip.ZipExtraField, org.apache.maven.surefire.shaded.org.codehaus.plexus.archiver.UnixStat, Cloneable
{

[...]

}

---

**Affects:** 1.0-alpha-15

**Attachments:**
- [mshade9-repro.diff](https://issues.apache.org/jira/secure/attachment/12719008/mshade9-repro.diff) (_1.79 kB_)

**Comment by jira-importer** [comment]
**[Daniel Fabulich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dfabulich)** commented

Updated to clarify that this is a relocation bug

**Comment by jira-importer** [comment]
**[Daniel Fabulich](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dfabulich)** commented

You should be able to apply this patch to surefire trunk revision 602310 to reproduce the problem.

**Comment by jira-importer** [comment]
**[Daniel Kulp](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=dkulp)** commented

Question: does this actually cause a problem using the shaded classes?

If you look at the rest of the decompiled class, every reference to UnixStat,ZipLong, ZipShort,  ZipExtraField are fully qualified.  It LOOKS like ASM is leaving some extra class refs in the constant pool, but those classes aren't ever actually referenced in the methods/fields.

To kind of test it, I created a simple test program that created a "new AsiExtraField" and called a few things on it and everything seemed to work without any of the plexus stuff available. (except the shaded jar)
