### ISSUE TITLE
[MSHADE-60] [PATCH] maven shade plugin fails if artifact dependencies contain artifacts that cannot be opened with JarFile class

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-shade-plugin#420]
**[Brane F. Gracnar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bfg)** opened **[MSHADE-60](https://issues.apache.org/jira/browse/MSHADE-60?redirect=false)** and commented

Maven Shade plugin fails to create an artifact if artifact dependecies
include artifacts that cannot be opened with JarFile JVM class.

This behaviour happens if someone puts something

\<dependencies>

---

**Affects:** 1.2.1

**Attachments:**
- [maven-shade-plugin-1.2.1.patch](https://issues.apache.org/jira/secure/attachment/12719002/maven-shade-plugin-1.2.1.patch) (_1.30 kB_)

**Issue Links:**
- [MSHADE-65](https://issues.apache.org/jira/browse/MSHADE-65) "Embedded error: error in opening zip file" with non-jar dependency

**Comment by jira-importer** [comment]
**[Brane F. Gracnar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bfg)** commented

Sorry, i hit enter button by accident.

Maven Shade plugin fails to create an artifact if artifact dependecies
include artifacts that cannot be opened with JarFile JVM class.

This behaviour happens if pom.xml contains something like this:

\<dependencies>
\<dependency>
\<artifactId>name\</artifactId>
\<groupId>com.example\</groupId>
\<version>1.0.0\</version>
\<type>pom\</type>
\</dependency>
\</dependencies>

I attached patch which skips inclusion of files, that cannot be included into artifact.

**Comment by jira-importer** [comment]
**[Brane F. Gracnar](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bfg)** commented

maven-shade-plugin version 1.2.1 fails with the following exception:

--- snip ---

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error creating shaded jar.

Embedded error: error in opening zip file
[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: Error creating shaded jar.
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalWithLifecycle(DefaultLifecycleExecutor.java:556)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:535)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating shaded jar.
at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:402)
at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
... 17 more
Caused by: java.util.zip.ZipException: error in opening zip file
at java.util.zip.ZipFile.open(Native Method)
at java.util.zip.ZipFile.\<init>(ZipFile.java:114)
at java.util.jar.JarFile.\<init>(JarFile.java:133)
at java.util.jar.JarFile.\<init>(JarFile.java:97)
at org.apache.maven.plugins.shade.DefaultShader.shade(DefaultShader.java:72)
at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:361)
... 19 more

--- snip ---

**Comment by jira-importer** [comment]
**[Mark Struberg](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=struberg)** commented

fixed in rev 812606

I didn't add the list of extensions, because they may be subject of change. But we now skip
depending artifacts of type=pom.
I also added an integration test to make sure that the transitive dependencies
pulled in via this pom-dependency gets picked up into the shaded jar.

If one has a dependency which cannot be opened via JarFile we now will at least
throw a verbose Exception with stating the exact file which failed. The user can then exclude
this artifact from shading.
