### ISSUE TITLE
[MSHADE-81] Poor error reporting

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-shade-plugin#443]
**[Pete Muir](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pmuir)** opened **[MSHADE-81](https://issues.apache.org/jira/browse/MSHADE-81?redirect=false)** and commented

When using XmlAppendingTransformer, I get this (fairly useless) error message:

on line 1: Premature end of file. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:1.3.3:shade (uber-jar) on project seam: Error creating shaded jar: org.jdom.input.JDOMParseException: Error on line 1: Premature end of file.
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:141)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:77)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:69)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:82)
at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:54)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.singleThreadedBuild(DefaultLifecycleExecutor.java:218)
at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:190)
at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:246)
at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:95)
at org.apache.maven.cli.MavenCli.execute(MavenCli.java:430)
at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:160)
at org.apache.maven.cli.MavenCli.main(MavenCli.java:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating shaded jar: org.jdom.input.JDOMParseException: Error on line 1: Premature end of file.
at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:489)
at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:105)
at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:133)
... 19 more
Caused by: java.lang.RuntimeException: org.jdom.input.JDOMParseException: Error on line 1: Premature end of file.
at org.apache.maven.plugins.shade.resource.XmlAppendingTransformer.processResource(XmlAppendingTransformer.java:89)
at org.apache.maven.plugins.shade.DefaultShader.resourceTransformed(DefaultShader.java:305)
at org.apache.maven.plugins.shade.DefaultShader.shade(DefaultShader.java:150)
at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:430)
... 21 more
Caused by: org.jdom.input.JDOMParseException: Error on line 1: Premature end of file.
at org.jdom.input.SAXBuilder.build(SAXBuilder.java:504)
at org.jdom.input.SAXBuilder.build(SAXBuilder.java:807)
at org.apache.maven.plugins.shade.resource.XmlAppendingTransformer.processResource(XmlAppendingTransformer.java:85)
... 24 more
Caused by: org.xml.sax.SAXParseException: Premature end of file.
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:195)
at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:174)
at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:388)
at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1414)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:1059)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:648)
at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:140)
at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:511)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:808)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:737)
at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:119)
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1205)
at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:522)
at org.jdom.input.SAXBuilder.build(SAXBuilder.java:489)
... 26 more

It would be significantly improved by changing line 89 to

throw new RuntimeException( "Error processing file " + resource, e );

---
No further details from [MSHADE-81](https://issues.apache.org/jira/browse/MSHADE-81?redirect=false)

**Comment by jira-importer** [comment]
**[Pete Muir](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pmuir)** commented

Actually, printing out resource is a good first step, but not enough, we need the name of the inputstream being worked on :-(

**Comment by jira-importer** [comment]
**[Pete Muir](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=pmuir)** commented

Without changing the API best bet looks like adding some logging for each file that is transformed around DefaultShader:150

**Comment by jira-importer** [comment]
**[Benjamin Bentmann](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bentmann)** commented

Improved exception and debug logging in [r983220](http://svn.apache.org/viewvc?view=revision&revision=983220).
