### ISSUE TITLE
[MSHADE-114] Specifying DontIncludeResourceTransformer before ManifestResourceTransformer causes PluginConfigurationException: Unable to parse configuration of mojo shade for parameter transformer: Cannot find setter...

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-shade-plugin#470]
**[Martin Stein](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=marstein)** opened **[MSHADE-114](https://issues.apache.org/jira/browse/MSHADE-114?redirect=false)** and commented

Using the transformer declaration:

```xml
<transformers>
 <transformer implementation="org.apache.maven.plugins.shade.resource.DontIncludeResourceTransformer">
   <resource>.so</resource>
 </transformer>
 <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
  <manifestEntries>
    <Premain-Class>org.jacoco.agent.${rt}.JacocoAgent</Premain-Class>
  </manifestEntries>
 </transformer>
</transformers>
```

causes the exception:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:1.4:shade (default) on project org.jacoco.agent.rt: Unable to parse configuration of mojo org.apache.maven.plugins:maven-shade-plugin:1.4:shade for parameter transformer: Cannot find setter, adder nor field in org.apache.maven.plugins.shade.resource.DontIncludeResourceTransformer for 'manifestEntries' -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:1.4:shade (default) on project org.jacoco.agent.rt: Unable to parse configuration of mojo org.apache.maven.plugins:maven-shade-plugin:1.4:shade for parameter transformer: Cannot find setter, adder nor field in org.apache.maven.plugins.shade.resource.DontIncludeResourceTransformer for 'manifestEntries'
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:221)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)
Caused by: org.apache.maven.plugin.PluginConfigurationException: Unable to parse configuration of mojo org.apache.maven.plugins:maven-shade-plugin:1.4:shade for parameter transformer: Cannot find setter, adder nor field in org.apache.maven.plugins.shade.resource.DontIncludeResourceTransformer for 'manifestEntries'
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:597)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:529)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 25 more
Caused by: org.codehaus.plexus.component.configurator.ComponentConfigurationException: Cannot find setter, adder nor field in org.apache.maven.plugins.shade.resource.DontIncludeResourceTransformer for 'manifestEntries'
	at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.<init>(ComponentValueSetter.java:95)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:158)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.fromConfiguration(ObjectWithFieldsConverter.java:89)
	at org.codehaus.plexus.component.configurator.converters.composite.ArrayConverter.fromChildren(ArrayConverter.java:129)
	at org.codehaus.plexus.component.configurator.converters.composite.ArrayConverter.fromConfiguration(ArrayConverter.java:91)
	at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:348)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:161)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:567)
	... 28 more
```

when the order of transformers is reversed the code passes; i.e. putting the `ManifestResourceTransformer` first.

(but still the DLL files are causing a problem: Error creating shaded jar: error in opening zip file C:\Users\mstein\.m2\repository\org\gosu-lang\gosu\gosu-native\1.0.1\gosu-native-1.0.1-jvmtiaccess-linux32.so)

---

**Affects:** 1.4

1 votes, 2 watchers

**Comment by jira-importer** [comment]
**[Vitalii Tymchyshyn](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=tivv)** commented

Still a problem in 2.0

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

I've added an integration-test in [r1481646](http://svn.apache.org/r1481646), but couldn't reproduce the issue.
Having a closer look at the stacktrace it looks more like a Maven-core issue, because the exception is thrown while preparing/configuring the shade-goal. The goal itself hasn't been executed yet.
