### ISSUE TITLE
[MSHADE-242] Plugin does not work with Java 9

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-shade-plugin#615]
**[Norman Maurer](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=norman)** opened **[MSHADE-242](https://issues.apache.org/jira/browse/MSHADE-242?redirect=false)** and commented

When trying to use the shade plugin with java9  I get:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.3:shade (default) on project netty-common: Error creating shaded jar: null: IllegalArgumentException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.3:shade (default) on project netty-common: Error creating shaded jar: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:537)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating shaded jar: null
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:540)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:201)
	at org.vafer.jdependency.Clazzpath.addClazzpathUnit(Clazzpath.java:132)
	at org.apache.maven.plugins.shade.filter.MinijarFilter.<init>(MinijarFilter.java:94)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.getFilters(ShadeMojo.java:814)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:446)
	... 22 more
```

---

**Affects:** 2.4.3

**Issue Links:**
- [FLINK-10285](https://issues.apache.org/jira/browse/FLINK-10285) Bump shade-plugin to 3.1.1

- [MDEP-559](https://issues.apache.org/jira/browse/MDEP-559) Java 9 bytecode cannot be parsed

- [MSHADE-258](https://issues.apache.org/jira/browse/MSHADE-258) RemappingClassAdapter is deprecated and throws an exception with ASM 6.0 beta

**Remote Links:**
- [#10 Valid names end with .class and don't contain a hyphen.
](https://github.com/tcurdt/jdependency/pull/10)

2 votes, 8 watchers

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Still waiting for the next ASM release, 6.0_ALPHA is not compatible with the current `module-info.class` implementation anymore.

**Comment by jira-importer** [comment]
**[Vincent Privat](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=don-vip)** commented

ASM 6.0 beta is released: https://mail.ow2.org/wws/arc/asm/2017-07/msg00002.html

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

So we're one step closer. First jdependency needs to do some stuff before we can upgrade.

**Comment by jira-importer** [comment]
**[Robert Scholte](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rfscholte)** commented

Fixed in [r1805501](http://svn.apache.org/viewvc?rev=1805501&view=rev)
