### ISSUE TITLE
[MSHADE-254] NullPointerException thrown by Maven Shade Plugin 3.0.0

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-shade-plugin#621]
**[Rafael Winterhalter](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=raphw)** opened **[MSHADE-254](https://issues.apache.org/jira/browse/MSHADE-254?redirect=false)** and commented

When building my project https://github.com/raphw/byte-buddy, a null pointer exception is thrown with 3.0.0 that did not occur before:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade (default) on project byte-buddy: Execution default of goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade (default) on project byte-buddy: Execution default of goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.apache.maven.plugins:maven-shade-plugin:3.0.0:shade failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.resolveArtifactSources(ShadeMojo.java:730)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.processArtifactSelectors(ShadeMojo.java:627)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:425)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

---

**Affects:** 3.0.0

**Attachments:**
- [maven-shade-plugin-254-patch.diff](https://issues.apache.org/jira/secure/attachment/12879872/maven-shade-plugin-254-patch.diff) (_641 bytes_)

**Issue Links:**
- [MSHADE-247](https://issues.apache.org/jira/browse/MSHADE-247) NullpointerException when createSourcesJar = true and source jar cannot be found
 (_**"is superceded by"**_)

3 votes, 3 watchers

**Comment by jira-importer** [comment]
**[Jess](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=laphroaig15)** commented

The attached patch adds a guard to handle the null return behavior that occurs when a source jar is not published for a given shaded artifact.

**Comment by jira-importer** [comment]
**[Jaikiran Pai](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=jaikiran)** commented

It looks like this got fixed as part of MSHADE-247 which reports the same issue. This commit https://github.com/apache/maven-plugins/commit/c7aba5c5b045ab8af21e2e01c98a7fcdbfad0878 that is merged upstream, contains the fix.
