### ISSUE TITLE
[MSHADE-253] NullPointerException if minimizeJar == true && packaging == pom

### ISSUE THREAD

**Issue by jira-importer** [apache/maven-shade-plugin#623]
**[Aviem Zur](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=aviemzur)** opened **[MSHADE-253](https://issues.apache.org/jira/browse/MSHADE-253?redirect=false)** and commented

NullPointerException is thrown if minimizeJar == true && packaging == pom

Discovered when trying to configure shading a parent pom (With packaging == pom) so all submodules will shade using this configuration.

Stack trace:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.3:shade (*****) on project *****: Error creating shaded jar: null: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.4.3:shade (*****) on project *****: Error creating shaded jar: null
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error creating shaded jar: null
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:540)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at java.io.FileInputStream.<init>(FileInputStream.java:130)
	at org.apache.maven.plugins.shade.filter.MinijarFilter.<init>(MinijarFilter.java:94)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.getFilters(ShadeMojo.java:814)
	at org.apache.maven.plugins.shade.mojo.ShadeMojo.execute(ShadeMojo.java:446)
	... 22 more
```

---

**Issue Links:**
- [BEAM-1720](https://issues.apache.org/jira/browse/BEAM-1720) Consider minimization on shaded jars
 (_**"blocks"**_)
- [MSHADE-109](https://issues.apache.org/jira/browse/MSHADE-109) NullPointerException when using minimizeJar

**Remote Links:**
- [GitHub Pull Request #107
](https://github.com/apache/maven-plugins/pull/107)

**Comment by jira-importer** [comment]
**[Benson Margulies](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=bmargulies)** commented

Merged.
